//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA
    {
        public int id_con { get; set; }
        public Nullable<System.DateTime> data_con { get; set; }
        public string turno_con { get; set; }
        public Nullable<int> id_pac { get; set; }
        public Nullable<int> id_med { get; set; }
        public Nullable<int> id_conv { get; set; }
        public string sit_con { get; set; }
        public string med_con { get; set; }
    
        public virtual CONVENIO CONVENIO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual MEDICO MEDICO { get; set; }
    }
}
