//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ESPECIALIDADE()
        {
            this.Medicos = new HashSet<MEDICO>();
        }
    
        public int id_esp { get; set; }
        public string nome_esp { get; set; }
        public string des_esp { get; set; }
        public Nullable<int> id_med { get; set; }
    
        public virtual MEDICO MEDICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICO> Medicos { get; set; }
    }
}
