//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMEREQUISICAO
    {
        public int id_pac { get; set; }
        public Nullable<int> id_exa { get; set; }
        public Nullable<System.DateTime> data_exar { get; set; }
        public string obs_exar { get; set; }
        public Nullable<double> valor_exar { get; set; }
        public Nullable<int> id_conv { get; set; }
        public string med_exar { get; set; }
        public string sit_exar { get; set; }
        public int id_exar { get; set; }
    
        public virtual CONVENIO CONVENIO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual EXAME EXAME { get; set; }
    }
}
