//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAME
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXAME()
        {
            this.EXAMEREQUISICAOs = new HashSet<EXAMEREQUISICAO>();
        }
    
        public int id_exa { get; set; }
        public string nome_exa { get; set; }
        public string obs_exa { get; set; }
        public Nullable<int> id_conv { get; set; }
    
        public virtual CONVENIO CONVENIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXAMEREQUISICAO> EXAMEREQUISICAOs { get; set; }
    }
}
