//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEDICO()
        {
            this.CONSULTAs = new HashSet<CONSULTA>();
            this.ESPECIALIDADEs = new HashSet<ESPECIALIDADE>();
        }
    
        public int id_med { get; set; }
        public string nome_med { get; set; }
        public string end_med { get; set; }
        public Nullable<int> cpf_med { get; set; }
        public int tel_med { get; set; }
        public Nullable<int> crm_med { get; set; }
        public Nullable<int> qtd_aten_med { get; set; }
        public string cidade_med { get; set; }
        public string estado_med { get; set; }
        public Nullable<int> id_esp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA> CONSULTAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESPECIALIDADE> ESPECIALIDADEs { get; set; }
        public virtual ESPECIALIDADE ESPECIALIDADE { get; set; }
    }
}
